### ISSUE TITLE
Dependabot github action

### ISSUE THREAD

**Issue by Soviut** [Soviut/vite-vue3-template#5]
create `.github/dependabot.yml`

```yaml
# Configuration options:
# https://help.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'github-actions'
    directory: /
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'

  - package-ecosystem: 'npm'
    directory: /
    schedule:
      interval: 'weekly'
    labels:
      - 'dependencies'
    versioning-strategy: increase-if-necessary
```
